import {
  addDays,
  eachDayOfInterval,
  endOfMonth,
  format,
  isAfter,
  isBefore,
  isSameDay,
  parseISO,
  startOfMonth,
} from 'date-fns'
import { ko } from 'date-fns/locale'
import type { AppSettings, Plan, PlanStage, ScheduleItem } from '../types'
import { createId } from './ids'

export const toDateKey = (date: Date) => format(date, 'yyyy-MM-dd')
export const fromDateKey = (value: string) => parseISO(`${value}T12:00:00`)
export const todayKey = () => toDateKey(new Date())
export const formatKoreanDate = (value: string, pattern = 'M월 d일 EEEE') =>
  format(fromDateKey(value), pattern, { locale: ko })

export function isRestDay(date: string | Date, restWeekdays: number[], excludedDates: string[] = []) {
  const parsed = typeof date === 'string' ? fromDateKey(date) : date
  const key = toDateKey(parsed)
  return restWeekdays.includes(parsed.getDay()) || excludedDates.includes(key)
}

export function nextEligibleDate(
  date: string,
  restWeekdays: number[],
  excludedDates: string[] = [],
  includeCurrent = false,
) {
  if (restWeekdays.length >= 7) throw new Error('모든 요일이 휴식일이라 학습일을 계산할 수 없습니다.')
  let cursor = includeCurrent ? fromDateKey(date) : addDays(fromDateKey(date), 1)
  for (let guard = 0; guard < 3700; guard += 1) {
    if (!isRestDay(cursor, restWeekdays, excludedDates)) return toDateKey(cursor)
    cursor = addDays(cursor, 1)
  }
  throw new Error('계산 가능한 학습일을 찾지 못했습니다.')
}

export function nthEligibleDate(startDate: string, count: number, restWeekdays: number[], excludedDates: string[] = []) {
  if (count <= 0) throw new Error('목표 횟수는 1회 이상이어야 합니다.')
  let cursor = fromDateKey(startDate)
  let eligible = 0
  for (let guard = 0; guard < 3700; guard += 1) {
    const key = toDateKey(cursor)
    if (!isRestDay(cursor, restWeekdays, excludedDates)) {
      eligible += 1
      if (eligible === count) return key
    }
    cursor = addDays(cursor, 1)
  }
  throw new Error('목표 완료일이 계산 범위를 벗어났습니다.')
}

export const estimatedCompletionDate = nthEligibleDate

export function eligibleDatesInRange(startDate: string, endDate: string, restWeekdays: number[], excludedDates: string[] = []) {
  if (isAfter(fromDateKey(startDate), fromDateKey(endDate))) throw new Error('종료일은 시작일보다 빠를 수 없습니다.')
  return eachDayOfInterval({ start: fromDateKey(startDate), end: fromDateKey(endDate) })
    .filter((date) => !isRestDay(date, restWeekdays, excludedDates))
    .map(toDateKey)
}

function baseItem(plan: Plan, date: string, title: string, sequence?: number): ScheduleItem {
  const now = new Date().toISOString()
  return {
    id: createId('item'),
    planId: plan.id,
    title,
    date,
    allDay: true,
    plannedSequence: sequence,
    status: 'scheduled',
    isAutoGenerated: true,
    isRestDayOverride: false,
    estimatedMinutes: plan.targetMinutes ?? 50,
    notes: '',
    priority: 'normal',
    categoryId: plan.categoryId,
    createdAt: now,
    updatedAt: now,
  }
}

export function generateCountSchedule(plan: Plan, settings: AppSettings) {
  if (!plan.targetCount || plan.targetCount <= 0) throw new Error('횟수 완성형 계획에는 1회 이상의 목표가 필요합니다.')
  const rest = [...new Set([...settings.defaultRestWeekdays, ...plan.excludedWeekdays])]
  const endDate = nthEligibleDate(plan.startDate, plan.targetCount, rest, plan.excludedDates)
  const dates = eligibleDatesInRange(plan.startDate, endDate, rest, plan.excludedDates).slice(0, plan.targetCount)
  return dates.map((date, index) => baseItem(plan, date, `${plan.title.replace(/\s*\d+일\s*완성$/, '')} · Day ${index + 1}`, index + 1))
}

export function generateCumulativeSchedule(plan: Plan, stages: PlanStage[], settings: AppSettings) {
  if (!plan.endDate) throw new Error('누적 계획에는 종료일이 필요합니다.')
  const rest = [...new Set([...settings.defaultRestWeekdays, ...plan.excludedWeekdays])]
  const dates = eligibleDatesInRange(plan.startDate, plan.endDate, rest, plan.excludedDates)
  const ordered = [...stages].sort((a, b) => a.order - b.order)
  return dates.flatMap((date, eligibleIndex) => {
    const active = ordered.filter((stage) => {
      if (eligibleIndex < stage.unlockAfterEligibleDays) return false
      if (stage.keepPreviousStages) return true
      const next = ordered.find((candidate) => candidate.order === stage.order + 1)
      return !next || eligibleIndex < next.unlockAfterEligibleDays
    })
    return active.map((stage) => ({
      ...baseItem(plan, date, stage.title),
      stageId: stage.id,
      estimatedMinutes: stage.defaultDuration,
    }))
  })
}

export function generateSingleOrRecurringSchedule(plan: Plan, settings: AppSettings) {
  if (!plan.endDate || plan.recurrenceRule.frequency === 'none') return [baseItem(plan, plan.startDate, plan.title)]
  const rest = [...new Set([...settings.defaultRestWeekdays, ...plan.excludedWeekdays])]
  let dates = eligibleDatesInRange(plan.startDate, plan.endDate, rest, plan.excludedDates)
  const rule = plan.recurrenceRule
  if (rule.frequency === 'weekly' || rule.frequency === 'custom') {
    dates = dates.filter((date) => (rule.weekdays ?? []).includes(fromDateKey(date).getDay()))
  } else if (rule.frequency === 'weekdays') {
    dates = dates.filter((date) => ![0, 6].includes(fromDateKey(date).getDay()))
  } else if (rule.frequency === 'monthly') {
    const day = fromDateKey(plan.startDate).getDate()
    dates = dates.filter((date) => fromDateKey(date).getDate() === day)
  } else if ((rule.interval ?? 1) > 1) {
    dates = dates.filter((_, index) => index % (rule.interval ?? 1) === 0)
  }
  return dates.map((date, index) => baseItem(plan, date, plan.title, index + 1))
}

export function generateScheduleForPlan(plan: Plan, stages: PlanStage[], settings: AppSettings) {
  if (plan.planType === 'count') return generateCountSchedule(plan, settings)
  if (plan.planType === 'cumulative') return generateCumulativeSchedule(plan, stages, settings)
  return generateSingleOrRecurringSchedule(plan, settings)
}

export function protectCompletedAndRegenerate(existing: ScheduleItem[], generated: ScheduleItem[]) {
  const protectedItems = existing.filter((item) => item.status === 'completed' || !item.isAutoGenerated)
  const protectedKeys = new Set(protectedItems.map((item) => `${item.planId}:${item.stageId ?? ''}:${item.date}:${item.plannedSequence ?? ''}`))
  return [...protectedItems, ...generated.filter((item) => !protectedKeys.has(`${item.planId}:${item.stageId ?? ''}:${item.date}:${item.plannedSequence ?? ''}`))]
}

export function plannedAndActualProgress(planId: string, items: ScheduleItem[]) {
  const relevant = items.filter((item) => item.planId === planId && item.status !== 'cancelled')
  const completed = relevant.filter((item) => item.status === 'completed')
  return {
    planned: relevant.length,
    actual: completed.length,
    percent: relevant.length ? Math.round((completed.length / relevant.length) * 100) : 0,
    actualMinutes: completed.reduce((sum, item) => sum + (item.actualMinutes ?? item.estimatedMinutes), 0),
  }
}

export function achievementRate(items: ScheduleItem[]) {
  const eligible = items.filter((item) => !['cancelled', 'skipped'].includes(item.status))
  if (!eligible.length) return 0
  return Math.round((eligible.filter((item) => item.status === 'completed').length / eligible.length) * 100)
}

export function learningStreak(items: ScheduleItem[], settings: AppSettings, until = todayKey()) {
  const completedDates = new Set(items.filter((item) => item.status === 'completed').map((item) => item.date))
  let cursor = fromDateKey(until)
  let streak = 0
  for (let guard = 0; guard < 366; guard += 1) {
    const key = toDateKey(cursor)
    if (isRestDay(cursor, settings.defaultRestWeekdays)) {
      cursor = addDays(cursor, -1)
      continue
    }
    if (!completedDates.has(key)) break
    streak += 1
    cursor = addDays(cursor, -1)
  }
  return streak
}

export function monthGrid(month: Date, weekStartsOn: 0 | 1) {
  const start = startOfMonth(month)
  const end = endOfMonth(month)
  const offset = (start.getDay() - weekStartsOn + 7) % 7
  const gridStart = addDays(start, -offset)
  const tail = (weekStartsOn + 6 - end.getDay() + 7) % 7
  const gridEnd = addDays(end, tail)
  return eachDayOfInterval({ start: gridStart, end: gridEnd })
}

export function isWithinDateRange(date: string, start: string, end: string) {
  const value = fromDateKey(date)
  return (!isBefore(value, fromDateKey(start)) && !isAfter(value, fromDateKey(end))) || isSameDay(value, fromDateKey(start))
}
