import { describe, expect, it } from 'vitest'
import { createSampleData, defaultSettings } from '../data/seed'
import type { Plan, PlanStage, ScheduleItem } from '../types'
import {
  achievementRate,
  generateCumulativeSchedule,
  generateCountSchedule,
  isRestDay,
  nthEligibleDate,
} from './dates'

describe('학습 가능일 계산', () => {
  it('2026-07-15부터 일요일을 제외한 24번째 학습일은 2026-08-11이다', () => {
    expect(nthEligibleDate('2026-07-15', 24, [0])).toBe('2026-08-11')
  })

  it('일요일과 지정 제외일을 건너뛴다', () => {
    expect(isRestDay('2026-07-19', [0])).toBe(true)
    expect(nthEligibleDate('2026-12-31', 2, [0], ['2027-01-01'])).toBe('2027-01-02')
  })

  it('잘못된 목표와 모든 요일 휴식을 거부한다', () => {
    expect(() => nthEligibleDate('2026-07-15', 0, [0])).toThrow('1회 이상')
    expect(() => nthEligibleDate('2026-07-15', 1, [0, 1, 2, 3, 4, 5, 6])).toThrow('계산')
  })
})

describe('예시 계획 생성', () => {
  const sample = createSampleData()
  const certificatePlan = sample.plans.find((plan) => plan.id === 'plan-certificate-24')!
  const majorPlan = sample.plans.find((plan) => plan.id === 'plan-major-july')!
  const augustPlan = sample.plans.find((plan) => plan.id === 'plan-august-four-subjects')!

  it('정보처리기사 Day 1과 Day 24를 정확히 만든다', () => {
    const items = generateCountSchedule(certificatePlan, defaultSettings)
    expect(items).toHaveLength(24)
    expect(items[0]).toMatchObject({ date: '2026-07-15', plannedSequence: 1, title: '정보처리기사 실기 · Day 1' })
    expect(items.at(-1)).toMatchObject({ date: '2026-08-11', plannedSequence: 24, title: '정보처리기사 실기 · Day 24' })
  })

  it.each(['2026-07-19', '2026-07-26', '2026-08-02', '2026-08-09'])('%s 일요일에는 자동 학습을 만들지 않는다', (date) => {
    const items = generateCountSchedule(certificatePlan, defaultSettings)
    expect(items.some((item) => item.date === date)).toBe(false)
  })

  it('실제 학습일 3일마다 누적 과목을 추가한다', () => {
    const stages = sample.stages.filter((stage) => stage.planId === majorPlan.id)
    const items = generateCumulativeSchedule(majorPlan, stages, defaultSettings)
    const subjects = (date: string) => items.filter((item) => item.date === date).map((item) => item.title)
    expect(subjects('2026-07-16')).toEqual(['C언어'])
    expect(subjects('2026-07-18')).toEqual(['C언어'])
    expect(subjects('2026-07-19')).toEqual([])
    expect(subjects('2026-07-20')).toEqual(['C언어', '컴퓨터구조'])
    expect(subjects('2026-07-23')).toEqual(['C언어', '컴퓨터구조', '자료구조'])
    expect(subjects('2026-07-27')).toEqual(['C언어', '컴퓨터구조', '자료구조', '네트워크'])
  })

  it('8월 미시 계획은 26학습일에 네 과목씩 총 104개 일정을 만든다', () => {
    const items = sample.items.filter((item) => item.planId === augustPlan.id)
    expect(items).toHaveLength(104)
    expect(new Set(items.map((item) => item.date)).size).toBe(26)
    expect(items.filter((item) => item.date === '2026-08-01')).toHaveLength(4)
    expect(items.filter((item) => item.date === '2026-08-31')).toHaveLength(4)
    expect(items.filter((item) => item.date === '2026-08-01').reduce((sum, item) => sum + item.estimatedMinutes, 0)).toBe(145)
  })

  it.each(['2026-08-02', '2026-08-09', '2026-08-16', '2026-08-23', '2026-08-30'])('%s에는 8월 미시 학습 일정을 만들지 않는다', (date) => {
    expect(sample.items.some((item) => item.planId === augustPlan.id && item.date === date)).toBe(false)
  })

  it('박태순 네트워크 Lesson 69~71의 실제 목차를 정확한 날짜에 반영한다', () => {
    const networkNotes = (date: string) => sample.items.find((item) => item.planId === augustPlan.id && item.date === date && item.stageId === 'stage-august-network')?.notes
    expect(networkNotes('2026-08-25')).toContain('L69 웹 서비스·스크립트')
    expect(networkNotes('2026-08-27')).toContain('L70 인터넷 보안')
    expect(networkNotes('2026-08-29')).toContain('L71 보안 기술')
    expect(networkNotes('2026-08-31')).toContain('L58~71 전체 목차 복원')
  })

  it('모든 8월 일정에 과목별 결과물을 메모로 남긴다', () => {
    const items = sample.items.filter((item) => item.planId === augustPlan.id)
    expect(items.every((item) => item.notes.includes('오늘 남길 결과:'))).toBe(true)
  })
})

describe('진도 계산', () => {
  it('휴식일 항목을 만들지 않으므로 완료율을 낮추지 않는다', () => {
    const now = new Date().toISOString()
    const items: ScheduleItem[] = [
      { id: '1', title: '학습 1', date: '2026-07-18', allDay: true, status: 'completed', isAutoGenerated: true, isRestDayOverride: false, estimatedMinutes: 30, actualMinutes: 30, notes: '', priority: 'normal', createdAt: now, updatedAt: now },
      { id: '2', title: '학습 2', date: '2026-07-20', allDay: true, status: 'scheduled', isAutoGenerated: true, isRestDayOverride: false, estimatedMinutes: 30, notes: '', priority: 'normal', createdAt: now, updatedAt: now },
    ]
    expect(achievementRate(items)).toBe(50)
  })
})

// 모델 타입이 엔진 입력과 계속 호환되는지도 컴파일 단계에서 확인한다.
void ({} as Plan)
void ({} as PlanStage)
