import { describe, expect, it } from 'vitest'
import { timerActualMinutes, timerDisplaySeconds, timerElapsedSeconds, timerRecordedMinutes, timerTargetSeconds } from './itemTimer'
import type { ScheduleItem } from '../types'

const item = (patch: Partial<ScheduleItem> = {}): ScheduleItem => ({
  id: 'item-1',
  title: '테스트 공부',
  date: '2026-07-18',
  allDay: false,
  status: 'scheduled',
  isAutoGenerated: false,
  isRestDayOverride: false,
  estimatedMinutes: 90,
  notes: '',
  priority: 'normal',
  createdAt: '2026-07-18T00:00:00.000Z',
  updatedAt: '2026-07-18T00:00:00.000Z',
  ...patch,
})

describe('일정 타이머', () => {
  it('저장된 시간과 현재 실행 구간을 합산한다', () => {
    const running = item({ timerStatus: 'running', timerStartedAt: '2026-07-18T10:00:00.000Z', timerElapsedSeconds: 30 })
    expect(timerElapsedSeconds(running, Date.parse('2026-07-18T10:01:00.000Z'))).toBe(90)
  })

  it('목표 시간은 남은 시간을 0까지 차감한다', () => {
    const countdown = item({ timerMode: 'countdown', timerTargetMinutes: 90, timerStatus: 'paused', timerElapsedSeconds: 30 * 60 })
    expect(timerTargetSeconds(countdown)).toBe(90 * 60)
    expect(timerDisplaySeconds(countdown)).toBe(60 * 60)
    expect(timerDisplaySeconds({ ...countdown, timerElapsedSeconds: 100 * 60 })).toBe(0)
  })

  it('측정 시간을 분 단위 실제 공부량에 누적한다', () => {
    expect(timerRecordedMinutes(1)).toBe(1)
    expect(timerRecordedMinutes(90)).toBe(2)
    expect(timerActualMinutes(item({ actualMinutes: 20, timerBaseActualMinutes: 20 }), 90 * 60)).toBe(110)
  })
})
