import { describe, expect, it } from 'vitest'
import type { ScheduleItem } from '../types'
import { actualStudyMinutes, formatStudyMinutes, periodDateRange, plannedStudyMinutes, timeRangeMinutes } from './studyTime'

const now = new Date().toISOString()
const item = (patch: Partial<ScheduleItem> = {}): ScheduleItem => ({
  id: 'item-1', title: '학습', date: '2026-07-15', startTime: '09:00', endTime: '10:30', allDay: false,
  status: 'scheduled', isAutoGenerated: false, isRestDayOverride: false, estimatedMinutes: 30,
  notes: '', priority: 'normal', createdAt: now, updatedAt: now, ...patch,
})

describe('공부 시간 계산', () => {
  it('시작과 종료 시각의 차이를 분으로 계산한다', () => {
    expect(timeRangeMinutes('09:10', '11:00')).toBe(110)
    expect(timeRangeMinutes('09:00', '09:00')).toBeNull()
    expect(timeRangeMinutes('10:00', '09:00')).toBeNull()
  })

  it('입력한 시간 범위를 예상 시간보다 우선한다', () => {
    expect(plannedStudyMinutes(item())).toBe(90)
    expect(actualStudyMinutes(item())).toBe(0)
    expect(actualStudyMinutes(item({ status: 'completed' }))).toBe(90)
    expect(actualStudyMinutes(item({ status: 'completed', actualMinutes: 75 }))).toBe(75)
  })

  it('분을 읽기 쉬운 시간으로 표시한다', () => {
    expect(formatStudyMinutes(45)).toBe('45분')
    expect(formatStudyMinutes(90)).toBe('1시간 30분')
    expect(formatStudyMinutes(120)).toBe('2시간')
  })

  it('일간·주간·월간 범위를 계산한다', () => {
    expect(periodDateRange('2026-07-15', 'daily')).toEqual({ start: '2026-07-15', end: '2026-07-15' })
    expect(periodDateRange('2026-07-15', 'weekly')).toEqual({ start: '2026-07-13', end: '2026-07-19' })
    expect(periodDateRange('2026-07-15', 'monthly')).toEqual({ start: '2026-07-01', end: '2026-07-31' })
  })
})
