export type PlanType = 'single' | 'recurring' | 'count' | 'cumulative' | 'deadline' | 'habit' | 'free'
export type PlanStatus = 'active' | 'upcoming' | 'completed' | 'archived'
export type ScheduleStatus = 'scheduled' | 'in-progress' | 'completed' | 'missed' | 'skipped' | 'carried' | 'cancelled'
export type CategoryType = 'study' | 'exam' | 'assignment' | 'habit' | 'event' | 'project' | 'other'
export type PeriodType = 'daily' | 'weekly' | 'monthly'

export interface RecurrenceRule {
  frequency: 'none' | 'daily' | 'weekdays' | 'weekly' | 'monthly' | 'custom'
  interval?: number
  weekdays?: number[]
}

export interface Plan {
  id: string
  title: string
  description: string
  categoryId: string
  planType: PlanType
  startDate: string
  endDate?: string
  timezone: string
  targetCount?: number
  targetMinutes?: number
  recurrenceRule: RecurrenceRule
  excludedWeekdays: number[]
  excludedDates: string[]
  carryOverPolicy: 'ask' | 'keep' | 'next-eligible'
  color: string
  icon?: string
  status: PlanStatus
  createdAt: string
  updatedAt: string
}

export interface PlanStage {
  id: string
  planId: string
  order: number
  title: string
  unlockAfterEligibleDays: number
  keepPreviousStages: boolean
  color: string
  defaultDuration: number
}

export interface ScheduleItem {
  id: string
  planId?: string
  stageId?: string
  title: string
  date: string
  startTime?: string
  endTime?: string
  allDay: boolean
  plannedSequence?: number
  actualSequence?: number
  status: ScheduleStatus
  isAutoGenerated: boolean
  isRestDayOverride: boolean
  estimatedMinutes: number
  actualMinutes?: number
  completedAt?: string
  notes: string
  priority: 'low' | 'normal' | 'high'
  categoryId?: string
  createdAt: string
  updatedAt: string
}

export interface Category {
  id: string
  name: string
  type: CategoryType
  color: string
  icon?: string
  order: number
}

export interface Reflection {
  id: string
  date: string
  periodType: PeriodType
  good: string
  difficult: string
  improvement: string
  freeText: string
  createdAt: string
  updatedAt: string
}

export interface AppSettings {
  timezone: string
  weekStartsOn: 0 | 1
  defaultRestWeekdays: number[]
  defaultView: 'checklist' | 'timeline'
  dateFormat: 'yyyy.MM.dd' | 'yyyy-MM-dd'
  timeFormat: '12' | '24'
  notificationsEnabled: boolean
  reducedMotion: boolean
  fontScale: number
  appliedMigrations: string[]
  lastModifiedAt: string
}

export interface PlannerData {
  plans: Plan[]
  stages: PlanStage[]
  items: ScheduleItem[]
  categories: Category[]
  reflections: Reflection[]
  settings: AppSettings
}

export interface PlannerBackup {
  schemaVersion: 1
  exportedAt: string
  data: PlannerData
}
