import type { Category, Plan, PlannerData, ScheduleItem } from '../types'
import source from './englishGrammarPlan.md?raw'

export const ENGLISH_GRAMMAR_PLAN_ID = 'plan-english-grammar-six-months'
export const ENGLISH_GRAMMAR_CATEGORY_ID = 'cat-english'
export const ENGLISH_GRAMMAR_MIGRATION_ID = 'english-grammar-2026-08-to-2027-01-v1'

export const ENGLISH_GRAMMAR_CATEGORY = {
  id: ENGLISH_GRAMMAR_CATEGORY_ID,
  name: '영어',
  type: 'study',
  color: '#b78aa5',
  order: 3,
} satisfies Category

interface GrammarDay {
  date: string
  lines: string[]
}

function parseSchedule(value: string): GrammarDay[] {
  const days: GrammarDay[] = []
  let current: GrammarDay | null = null
  const flush = () => {
    if (current?.lines.length) days.push(current)
    current = null
  }

  for (const rawLine of value.split(/\r?\n/)) {
    const line = rawLine.trim()
    if (line === '```') {
      flush()
      continue
    }
    const date = line.match(/^(\d{2})\/(\d{2})\([^)]+\)$/)
    if (date) {
      flush()
      const month = Number(date[1])
      const year = month === 1 ? 2027 : 2026
      current = { date: `${year}-${date[1]}-${date[2]}`, lines: [] }
      continue
    }
    if (current && line && !line.startsWith('#')) current.lines.push(line)
  }
  flush()
  return days
}

export const englishGrammarSchedule = parseSchedule(source)

function itemTitle(day: GrammarDay) {
  if (day.date < '2026-10-01') {
    const topic = day.lines[0]?.match(/^\[([^\]]+)\]/)?.[1] ?? '문마·해커스 학습'
    return `영문법 · ${topic}`
  }
  if (day.date < '2026-12-01') return '영문법 · 문마·해커스 + START'
  return '영문법 · 문마·해커스 + START + ESSENTIAL'
}

function targetMinutes(date: string) {
  if (date < '2026-10-01') return 100
  if (date < '2026-12-01') return 110
  return 135
}

function timeGuide(date: string) {
  if (date < '2026-10-01') return '권장 학습 시간: 90~110분'
  if (date < '2026-12-01') return '권장 학습 시간: 100~120분'
  return '권장 학습 시간: 120~150분'
}

export function createEnglishGrammarTemplate(categoryId = ENGLISH_GRAMMAR_CATEGORY_ID) {
  const now = '2026-07-16T09:00:00+09:00'
  const plan: Plan = {
    id: ENGLISH_GRAMMAR_PLAN_ID,
    title: '6개월 영문법 완주',
    description: '문마·해커스 16개 Chapter, 어법끝 START Part I·II, 어법끝 ESSENTIAL 34개 Testing Point와 실전 모의고사 5회를 일요일 없이 완주합니다.',
    categoryId,
    planType: 'recurring',
    startDate: '2026-08-01',
    endDate: '2027-01-30',
    timezone: 'Asia/Seoul',
    targetMinutes: 120,
    recurrenceRule: { frequency: 'daily', interval: 1 },
    excludedWeekdays: [0],
    excludedDates: [],
    carryOverPolicy: 'ask',
    color: '#b78aa5',
    status: 'upcoming',
    createdAt: now,
    updatedAt: now,
  }
  const items: ScheduleItem[] = englishGrammarSchedule.map((day, index) => ({
    id: `item-english-grammar-${day.date}`,
    planId: plan.id,
    title: itemTitle(day),
    date: day.date,
    allDay: true,
    plannedSequence: index + 1,
    status: 'scheduled',
    isAutoGenerated: true,
    isRestDayOverride: false,
    estimatedMinutes: targetMinutes(day.date),
    notes: `${day.lines.join('\n')}\n\n${timeGuide(day.date)}`,
    priority: 'normal',
    categoryId,
    createdAt: now,
    updatedAt: now,
  }))
  return { plan, items }
}

export function ensureEnglishGrammarPlan(data: PlannerData): { data: PlannerData; changed: boolean } {
  const appliedMigrations = data.settings.appliedMigrations ?? []
  if (appliedMigrations.includes(ENGLISH_GRAMMAR_MIGRATION_ID)) return { data, changed: false }

  const now = new Date().toISOString()
  const category = data.categories.find((candidate) => candidate.id === ENGLISH_GRAMMAR_CATEGORY_ID)
    ?? ENGLISH_GRAMMAR_CATEGORY
  const template = createEnglishGrammarTemplate(category.id)
  const existingPlan = data.plans.find((plan) => plan.id === ENGLISH_GRAMMAR_PLAN_ID)
  const existingItems = data.items.filter((item) => item.planId === ENGLISH_GRAMMAR_PLAN_ID)
  const existingByDate = new Map(existingItems.map((item) => [item.date, item]))
  const templateDates = new Set(template.items.map((item) => item.date))
  const mergedItems = template.items.map((item) => {
    const previous = existingByDate.get(item.date)
    if (!previous) return item
    return {
      ...item,
      id: previous.id,
      title: previous.title,
      status: previous.status,
      isAutoGenerated: previous.isAutoGenerated,
      estimatedMinutes: previous.estimatedMinutes,
      actualMinutes: previous.actualMinutes,
      actualSequence: previous.actualSequence,
      completedAt: previous.completedAt,
      notes: previous.notes,
      priority: previous.priority,
      createdAt: previous.createdAt,
      updatedAt: now,
    }
  })
  const unmatchedUserItems = existingItems.filter((item) => !item.isAutoGenerated && !templateDates.has(item.date))
  const nextPlan = existingPlan ? {
    ...existingPlan,
    startDate: template.plan.startDate,
    endDate: template.plan.endDate,
    excludedWeekdays: [...new Set([...existingPlan.excludedWeekdays, 0])],
    updatedAt: now,
  } : template.plan
  return {
    changed: true,
    data: {
      ...data,
      categories: data.categories.some((candidate) => candidate.id === category.id) ? data.categories : [...data.categories, category],
      plans: existingPlan ? data.plans.map((plan) => plan.id === ENGLISH_GRAMMAR_PLAN_ID ? nextPlan : plan) : [...data.plans, nextPlan],
      items: [...data.items.filter((item) => item.planId !== ENGLISH_GRAMMAR_PLAN_ID), ...mergedItems, ...unmatchedUserItems],
      settings: {
        ...data.settings,
        defaultRestWeekdays: [...new Set([...data.settings.defaultRestWeekdays, 0])],
        appliedMigrations: [...appliedMigrations, ENGLISH_GRAMMAR_MIGRATION_ID],
        lastModifiedAt: now,
      },
    },
  }
}
