import type { AppSettings, Category, Plan, PlannerData, PlanStage, ScheduleItem } from '../types'
import { eligibleDatesInRange, fromDateKey, generateCumulativeSchedule, generateCountSchedule } from '../lib/dates'
import { createAugustCurriculumItems } from './augustCurriculum'

export const AUGUST_PLAN_ID = 'plan-august-four-subjects'
export const AUGUST_CURRICULUM_MIGRATION_ID = '2026-august-four-subjects-v1'
export const CERTIFICATE_PLAN_ID = 'plan-certificate-24'
export const CERTIFICATE_START_MIGRATION_ID = 'certificate-start-2026-07-16-v1'
export const MAJOR_PLAN_ID = 'plan-major-july'
export const EXERCISE_PLAN_ID = 'plan-tanbang-underpass-exercise'
export const STUDY_CAFE_PLAN_ID = 'plan-study-cafe-adaptation'
export const SUMMER_ROUTINE_MIGRATION_ID = 'summer-routine-2026-07-27-v1'

const SEED_NOW = '2026-07-16T09:00:00+09:00'

export const defaultSettings: AppSettings = {
  timezone: 'Asia/Seoul',
  weekStartsOn: 1,
  defaultRestWeekdays: [0],
  defaultView: 'checklist',
  dateFormat: 'yyyy.MM.dd',
  timeFormat: '24',
  notificationsEnabled: false,
  reducedMotion: false,
  fontScale: 1,
  appliedMigrations: [],
  lastModifiedAt: SEED_NOW,
}

const categories: Category[] = [
  { id: 'cat-cert', name: '자격증', type: 'study', color: '#75a99f', order: 0 },
  { id: 'cat-major', name: '전공', type: 'study', color: '#8096c7', order: 1 },
  { id: 'cat-life', name: '생활', type: 'event', color: '#dc9a7c', order: 2 },
]

function basePlan(overrides: Partial<Plan> & Pick<Plan, 'id' | 'title' | 'categoryId' | 'planType' | 'startDate' | 'color'>): Plan {
  return {
    description: '',
    timezone: 'Asia/Seoul',
    recurrenceRule: { frequency: 'daily', interval: 1 },
    excludedWeekdays: [0],
    excludedDates: [],
    carryOverPolicy: 'ask',
    status: 'active',
    createdAt: SEED_NOW,
    updatedAt: SEED_NOW,
    ...overrides,
  }
}

function createAugustTemplate(categoryId: string) {
  const plan = basePlan({
    id: AUGUST_PLAN_ID,
    title: '2026년 8월 4과목 미시 학습',
    description: 'C언어·컴퓨터구조·자료구조·네트워크를 매 학습일 모두 공부하고, 과목별 결과물을 하나씩 남깁니다.',
    categoryId,
    planType: 'recurring',
    startDate: '2026-07-27',
    endDate: '2026-08-25',
    targetMinutes: 145,
    color: '#718f9f',
    status: 'upcoming',
  })
  const stages: PlanStage[] = [
    { id: 'stage-august-c', planId: plan.id, order: 0, title: 'C언어', unlockAfterEligibleDays: 0, keepPreviousStages: true, color: '#8096c7', defaultDuration: 40 },
    { id: 'stage-august-architecture', planId: plan.id, order: 1, title: '컴퓨터구조', unlockAfterEligibleDays: 0, keepPreviousStages: true, color: '#75a99f', defaultDuration: 40 },
    { id: 'stage-august-data', planId: plan.id, order: 2, title: '자료구조', unlockAfterEligibleDays: 0, keepPreviousStages: true, color: '#9a8cc4', defaultDuration: 40 },
    { id: 'stage-august-network', planId: plan.id, order: 3, title: '네트워크', unlockAfterEligibleDays: 0, keepPreviousStages: true, color: '#d59a72', defaultDuration: 25 },
  ]
  return { plan, stages, items: createAugustCurriculumItems(plan, stages) }
}

function timedItem(plan: Plan, date: string, title: string, startTime: string, endTime: string, estimatedMinutes: number, sequence: number, notes: string): ScheduleItem {
  return {
    id: `item-${plan.id}-${date}`,
    planId: plan.id,
    title,
    date,
    startTime,
    endTime,
    allDay: false,
    plannedSequence: sequence,
    status: 'scheduled',
    isAutoGenerated: true,
    isRestDayOverride: false,
    estimatedMinutes,
    notes,
    priority: 'normal',
    categoryId: plan.categoryId,
    createdAt: SEED_NOW,
    updatedAt: SEED_NOW,
  }
}

function createExerciseTemplate(categoryId: string) {
  const plan = basePlan({
    id: EXERCISE_PLAN_ID,
    title: '탄방역 지하보도 운동',
    description: '방학이 끝나는 8월 말까지 일요일을 제외하고 매일 오후 4시 50분부터 5시 50분까지 운동합니다.',
    categoryId,
    planType: 'habit',
    startDate: '2026-07-16',
    endDate: '2026-08-31',
    targetMinutes: 60,
    color: '#dc9a7c',
  })
  const dates = eligibleDatesInRange(plan.startDate, plan.endDate!, [0], plan.excludedDates)
  const items = dates.map((date, index) => timedItem(
    plan,
    date,
    plan.title,
    '16:50',
    '17:50',
    60,
    index + 1,
    '탄방역 지하보도에서 1시간 운동. 일요일은 완전 휴식합니다.',
  ))
  return { plan, items }
}

const studyCafeAdaptation = [
  { date: '2026-07-15', startTime: '18:30', endTime: '19:30', minutes: 60 },
  { date: '2026-07-16', startTime: '18:30', endTime: '20:00', minutes: 90 },
  { date: '2026-07-17', startTime: '18:30', endTime: '20:30', minutes: 120 },
  { date: '2026-07-18', startTime: '18:30', endTime: '21:00', minutes: 150 },
  { date: '2026-07-20', startTime: '18:30', endTime: '21:30', minutes: 180 },
  { date: '2026-07-21', startTime: '18:30', endTime: '22:00', minutes: 210 },
  { date: '2026-07-22', startTime: '18:30', endTime: '23:00', minutes: 270 },
  { date: '2026-07-23', startTime: '18:30', endTime: '00:00', minutes: 330 },
  { date: '2026-07-24', startTime: '18:30', endTime: '01:00', minutes: 390 },
  { date: '2026-07-25', startTime: '18:00', endTime: '02:00', minutes: 480 },
] as const

function createStudyCafeTemplate(categoryId: string) {
  const plan = basePlan({
    id: STUDY_CAFE_PLAN_ID,
    title: '스터디카페 적응·유지 루틴',
    description: '7월 25일까지 체류 시간을 단계적으로 늘리고, 7월 27일부터 8월 말까지 오후 6시부터 다음 날 새벽 2시까지 8시간을 유지합니다.',
    categoryId,
    planType: 'habit',
    startDate: '2026-07-15',
    endDate: '2026-08-31',
    targetMinutes: 480,
    color: '#b68cbd',
  })
  const adaptationItems = studyCafeAdaptation.map((entry, index) => {
    const item = timedItem(
      plan,
      entry.date,
      `스터디카페 적응 · ${entry.minutes / 60 % 1 === 0 ? `${entry.minutes / 60}시간` : `${Math.floor(entry.minutes / 60)}시간 ${entry.minutes % 60}분`}`,
      entry.startTime,
      entry.endTime,
      entry.minutes,
      index + 1,
      '이번 단계의 목표는 공부 성과가 아니라 정해진 시간까지 자리에 머무는 연습입니다.',
    )
    return index === 0 ? {
      ...item,
      status: 'completed' as const,
      actualMinutes: 60,
      actualSequence: 1,
      completedAt: '2026-07-15T19:30:00+09:00',
    } : item
  })
  const maintenanceDates = eligibleDatesInRange('2026-07-27', plan.endDate!, [0], plan.excludedDates)
  const maintenanceItems = maintenanceDates.map((date, index) => timedItem(
    plan,
    date,
    '스터디카페 8시간 유지',
    '18:00',
    '02:00',
    480,
    adaptationItems.length + index + 1,
    '오후 6시에 앉아 다음 날 새벽 2시까지 유지합니다. 기존 학습 계획은 이 시간 안에서 진행합니다.',
  ))
  return { plan, items: [...adaptationItems, ...maintenanceItems] }
}

export function createSampleData(): PlannerData {
  const certificatePlan = basePlan({
    id: CERTIFICATE_PLAN_ID,
    title: '정보처리기사 실기 24일 완성',
    description: '일요일을 제외한 24번의 학습으로 실기 범위를 완주합니다.',
    categoryId: 'cat-cert',
    planType: 'count',
    startDate: '2026-07-27',
    targetCount: 24,
    targetMinutes: 70,
    color: '#75a99f',
  })
  const cumulativePlan = basePlan({
    id: MAJOR_PLAN_ID,
    title: '7월 전공 누적 학습',
    description: '실제 학습일 3일마다 다음 전공 과목을 더합니다.',
    categoryId: 'cat-major',
    planType: 'cumulative',
    startDate: '2026-07-27',
    endDate: '2026-08-11',
    targetMinutes: 35,
    color: '#8096c7',
  })
  const augustTemplate = createAugustTemplate('cat-major')
  const augustPlan = augustTemplate.plan
  const exerciseTemplate = createExerciseTemplate('cat-life')
  const studyCafeTemplate = createStudyCafeTemplate('cat-life')
  const cumulativeStages: PlanStage[] = [
    { id: 'stage-c', planId: cumulativePlan.id, order: 0, title: 'C언어', unlockAfterEligibleDays: 0, keepPreviousStages: true, color: '#8096c7', defaultDuration: 35 },
    { id: 'stage-architecture', planId: cumulativePlan.id, order: 1, title: '컴퓨터구조', unlockAfterEligibleDays: 3, keepPreviousStages: true, color: '#9a8cc4', defaultDuration: 35 },
    { id: 'stage-data', planId: cumulativePlan.id, order: 2, title: '자료구조', unlockAfterEligibleDays: 6, keepPreviousStages: true, color: '#ca8fa6', defaultDuration: 35 },
    { id: 'stage-network', planId: cumulativePlan.id, order: 3, title: '네트워크', unlockAfterEligibleDays: 9, keepPreviousStages: true, color: '#d59a72', defaultDuration: 35 },
  ]
  const augustStages = augustTemplate.stages
  const stages = [...cumulativeStages, ...augustStages]
  const plans = [certificatePlan, cumulativePlan, augustPlan, exerciseTemplate.plan, studyCafeTemplate.plan]
  const items = [
    ...generateCountSchedule(certificatePlan, defaultSettings),
    ...generateCumulativeSchedule(cumulativePlan, cumulativeStages, defaultSettings),
    ...augustTemplate.items,
    ...exerciseTemplate.items,
    ...studyCafeTemplate.items,
  ]
  return { plans, stages, items, categories, reflections: [], settings: { ...defaultSettings, appliedMigrations: [AUGUST_CURRICULUM_MIGRATION_ID, CERTIFICATE_START_MIGRATION_ID, SUMMER_ROUTINE_MIGRATION_ID], lastModifiedAt: new Date().toISOString() } }
}

export function createEmptyData(): PlannerData {
  return { plans: [], stages: [], items: [], categories: [...categories], reflections: [], settings: { ...defaultSettings, appliedMigrations: [AUGUST_CURRICULUM_MIGRATION_ID, CERTIFICATE_START_MIGRATION_ID, SUMMER_ROUTINE_MIGRATION_ID], lastModifiedAt: new Date().toISOString() } }
}

export function ensureAugustCurriculum(data: PlannerData): { data: PlannerData; added: boolean } {
  const appliedMigrations = data.settings.appliedMigrations ?? []
  if (appliedMigrations.includes(AUGUST_CURRICULUM_MIGRATION_ID)) return { data, added: false }

  const nextSettings = {
    ...data.settings,
    appliedMigrations: [...appliedMigrations, AUGUST_CURRICULUM_MIGRATION_ID],
    lastModifiedAt: new Date().toISOString(),
  }
  if (data.plans.some((plan) => plan.id === AUGUST_PLAN_ID)) {
    return { data: { ...data, settings: nextSettings }, added: false }
  }

  let nextCategories = data.categories
  let category = data.categories.find((candidate) => candidate.id === 'cat-major')
    ?? data.categories.find((candidate) => candidate.type === 'study')
    ?? data.categories[0]
  if (!category) {
    category = { id: 'cat-major', name: '전공', type: 'study', color: '#8096c7', order: 0 }
    nextCategories = [category]
  }

  const template = createAugustTemplate(category.id)
  const stageIds = new Set(template.stages.map((stage) => stage.id))
  return {
    added: true,
    data: {
      ...data,
      categories: nextCategories,
      plans: [...data.plans, template.plan],
      stages: [...data.stages.filter((stage) => stage.planId !== AUGUST_PLAN_ID && !stageIds.has(stage.id)), ...template.stages],
      items: [...data.items.filter((item) => item.planId !== AUGUST_PLAN_ID && !item.id.startsWith('item-august-')), ...template.items],
      settings: nextSettings,
    },
  }
}

export function ensureCertificateStartDate(data: PlannerData): { data: PlannerData; changed: boolean } {
  const appliedMigrations = data.settings.appliedMigrations ?? []
  if (appliedMigrations.includes(CERTIFICATE_START_MIGRATION_ID)) return { data, changed: false }

  const now = new Date().toISOString()
  const nextSettings = {
    ...data.settings,
    appliedMigrations: [...appliedMigrations, CERTIFICATE_START_MIGRATION_ID],
    lastModifiedAt: now,
  }
  const plan = data.plans.find((candidate) => candidate.id === CERTIFICATE_PLAN_ID)
  if (!plan) return { data: { ...data, settings: nextSettings }, changed: false }

  const updatedPlan = { ...plan, startDate: '2026-07-16', updatedAt: now }
  const generated = generateCountSchedule(updatedPlan, data.settings)
  const dateBySequence = new Map(generated.map((item) => [item.plannedSequence, item.date]))
  return {
    changed: true,
    data: {
      ...data,
      plans: data.plans.map((candidate) => candidate.id === CERTIFICATE_PLAN_ID ? updatedPlan : candidate),
      items: data.items.map((item) => {
        if (item.planId !== CERTIFICATE_PLAN_ID || !item.plannedSequence) return item
        const date = dateBySequence.get(item.plannedSequence)
        return date ? { ...item, date, updatedAt: now } : item
      }),
      settings: nextSettings,
    },
  }
}

function keyedPlanItems(items: ScheduleItem[], planId: string) {
  const sorted = [...items].sort((a, b) => a.date.localeCompare(b.date)
    || (a.stageId ?? '').localeCompare(b.stageId ?? '')
    || (a.plannedSequence ?? 0) - (b.plannedSequence ?? 0)
    || a.id.localeCompare(b.id))
  if (planId === MAJOR_PLAN_ID) {
    const stageCounts = new Map<string, number>()
    return sorted.map((item) => {
      const stage = item.stageId ?? 'none'
      const occurrence = (stageCounts.get(stage) ?? 0) + 1
      stageCounts.set(stage, occurrence)
      return { item, key: `${stage}:${occurrence}` }
    })
  }
  if (planId === AUGUST_PLAN_ID) {
    return sorted.map((item) => ({ item, key: `${item.stageId ?? 'none'}:${item.plannedSequence ?? item.date}` }))
  }
  return sorted.map((item) => ({ item, key: String(item.plannedSequence ?? item.date) }))
}

function mergePlanItems(existing: ScheduleItem[], template: ScheduleItem[], planId: string, now: string) {
  const existingByKey = new Map(keyedPlanItems(existing, planId).map(({ item, key }) => [key, item]))
  const usedIds = new Set<string>()
  const aligned = keyedPlanItems(template, planId).map(({ item, key }) => {
    const previous = existingByKey.get(key)
    if (!previous) return item
    usedIds.add(previous.id)
    return {
      ...item,
      id: previous.id,
      title: previous.title,
      startTime: previous.startTime ?? item.startTime,
      endTime: previous.endTime ?? item.endTime,
      allDay: (previous.startTime ?? item.startTime) ? false : item.allDay,
      status: previous.status,
      isAutoGenerated: previous.isAutoGenerated,
      estimatedMinutes: previous.estimatedMinutes,
      actualMinutes: previous.actualMinutes,
      actualSequence: previous.actualSequence,
      completedAt: previous.completedAt,
      notes: previous.notes,
      priority: previous.priority,
      createdAt: previous.createdAt,
      updatedAt: now,
    }
  })
  const extraUserItems = existing.filter((item) => !usedIds.has(item.id) && !item.isAutoGenerated && fromDateKey(item.date).getDay() !== 0)
  return [...aligned, ...extraUserItems]
}

export function ensureSummerRoutine(data: PlannerData): { data: PlannerData; changed: boolean } {
  const appliedMigrations = data.settings.appliedMigrations ?? []
  if (appliedMigrations.includes(SUMMER_ROUTINE_MIGRATION_ID)) return { data, changed: false }

  const now = new Date().toISOString()
  const template = createSampleData()
  const targetPlanIds = new Set([CERTIFICATE_PLAN_ID, MAJOR_PLAN_ID, AUGUST_PLAN_ID, EXERCISE_PLAN_ID, STUDY_CAFE_PLAN_ID])
  const templatePlans = new Map(template.plans.map((plan) => [plan.id, plan]))
  const existingPlanIds = new Set(data.plans.map((plan) => plan.id))
  const plans = [
    ...data.plans.map((plan) => {
      const next = templatePlans.get(plan.id)
      if (!next) return plan
      return {
        ...plan,
        startDate: next.startDate,
        endDate: next.endDate,
        excludedWeekdays: [...new Set([...plan.excludedWeekdays, 0])],
        updatedAt: now,
      }
    }),
    ...template.plans.filter((plan) => !existingPlanIds.has(plan.id)),
  ]
  const existingStageIds = new Set(data.stages.map((stage) => stage.id))
  const stages = [...data.stages, ...template.stages.filter((stage) => !existingStageIds.has(stage.id))]
  const items = [
    ...data.items.filter((item) => !item.planId || !targetPlanIds.has(item.planId)),
    ...template.plans.flatMap((plan) => mergePlanItems(
      data.items.filter((item) => item.planId === plan.id),
      template.items.filter((item) => item.planId === plan.id),
      plan.id,
      now,
    )),
  ]
  const existingCategoryIds = new Set(data.categories.map((category) => category.id))
  const nextSettings = {
    ...data.settings,
    defaultRestWeekdays: [...new Set([...data.settings.defaultRestWeekdays, 0])],
    appliedMigrations: [...appliedMigrations, SUMMER_ROUTINE_MIGRATION_ID],
    lastModifiedAt: now,
  }
  return {
    changed: true,
    data: {
      ...data,
      plans,
      stages,
      items,
      categories: [...data.categories, ...template.categories.filter((category) => !existingCategoryIds.has(category.id))],
      settings: nextSettings,
    },
  }
}
